name: Count Files

on: [push]

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Count the number of files
        uses: omagdy7/count_files@v1.0
        with:
          path: ./
